### ISSUE TITLE
Add flatMapDrop

### ISSUE THREAD

**Issue by GianfrancoMS** [akarnokd/kotlin-flow-extensions#13]
Similar to the [RxJavaExtensions](https://github.com/akarnokd/RxJavaExtensions#observabletransformersflatmapdrop), it would be nice to have a FlatMapDrop operator for Flow.

**Comment by akarnokd** [comment]
Closing via [v0.0.3](https://github.com/akarnokd/kotlin-flow-extensions/releases/tag/v0.0.3).
