### ISSUE TITLE
Get current value from BehaviorSubject

### ISSUE THREAD

**Issue by rougsig** [akarnokd/kotlin-flow-extensions#31]
In some cases it would be preferable to get current value from BehaviorSubject, but the method of getting it has been missing in current release. Please consider adding this feature in future releases.

**Comment by akarnokd** [comment]
Sure. It may take a few days till I can come back to this myself, but you can go ahead and do a PR.

**Comment by rougsig** [comment]
Thx. I'm going to make PR.

**Comment by rougsig** [comment]
https://github.com/akarnokd/kotlin-flow-extensions/pull/32

**Comment by akarnokd** [comment]
Closing via #32.
