### ISSUE TITLE
[Feature Request] Adding UnicastWorkSubject and UnicastSubject

### ISSUE THREAD

**Issue by R4md4c** [akarnokd/kotlin-flow-extensions#41]
Thanks a lot for your very helpful lib. 

It would be nice if [UnicastWorkSubject ](https://akarnokd.github.io/RxJavaExtensions/javadoc/hu/akarnokd/rxjava3/subjects/UnicastWorkSubject.html) and [UnicastSubject ](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/subjects/UnicastSubject.html) Kotlin Flow equivalent could be added.

**Comment by caeduk** [comment]
I was about to make the same feature request.

👍

**Comment by akarnokd** [comment]
Closing via [v0.0.8](https://github.com/akarnokd/kotlin-flow-extensions/releases/tag/v0.0.8).
