### ISSUE TITLE
Publish with multiple consumers doesn't work as expected

### ISSUE THREAD

**Issue by sskrla** [akarnokd/kotlin-flow-extensions#46]
This may be a misunderstanding on my part, but coming from using Reactor (and in fact, porting code written in Reactor) I would expect the following flow to pass:

```
    @Test
    fun `publish multiple consumers`() = runBlocking {
        arrayOf(1, 2, 3, 4, 5)
                .asFlow()
                .publish {
                    shared ->
                        merge(shared.filter { it % 2 == 1}, shared.filter { it % 2 == 0})
                }
                .assertResult(1, 2, 3, 4, 5)
    }
```

But in reality, the flow completes yielding no results. Using `flatMapConcat` will yield results from the first sequence, and not the second.

**Comment by akarnokd** [comment]
What do you mean by yielding no results? Does the assertion fail?

**Comment by sskrla** [comment]
Updated the code with a test I've added to the project. It fails with:

```
expected:<[1, 2, 3, 4, 5]> but was:<[]>
Expected :[1, 2, 3, 4, 5]
Actual   :[]
```

**Comment by akarnokd** [comment]
For some reason, `merge` doesn't start collecting the inner subject and the main source just runs to completion without observers. I have no idea why that is. 

I know they had quite some trouble with their `shareIn` operator too. https://github.com/Kotlin/kotlinx.coroutines/issues/2047

**Comment by akarnokd** [comment]
This is a complicated issue and I'm not sure how to solve it without asking the programmer for more parameters.

The workaround I suggest is in the form of an overload to [publish](https://github.com/akarnokd/kotlin-flow-extensions#flowpublish) where you can tell it to wait for these 2 inner collectors.

Closing via https://github.com/akarnokd/kotlin-flow-extensions/commit/adec011dbdb826b85477550efc35d41bddf4dd06
