### ISSUE TITLE
[Feature Request] Flow.onCreate(action: Block)

### ISSUE THREAD

**Issue by iRYO400** [akarnokd/kotlin-flow-extensions#58]
Hi! 
Can you provide an example, how to make such an extension which will be **called once**, when initial value passed?

**Comment by akarnokd** [comment]
I have no idea what you are talking about. 

Please ask such questions on [StackOverflow](https://stackoverflow.com/questions/tagged/kotlin-coroutines) or on the [coroutines](https://github.com/Kotlin/kotlinx.coroutines/issues) issue list as they are the primary experts on how to expand their `Flow` solution.

**Comment by iRYO400** [comment]
Got you 👌
