### ISSUE TITLE
Is there any plan to add `concatArrayEager(...)` to this library?

### ISSUE THREAD

**Issue by ExpensiveBelly** [akarnokd/kotlin-flow-extensions#92]

**Comment by akarnokd** [comment]
No particular plan to add any operators from RxJava at the moment. What is your use case for this particular operator?

**Comment by ExpensiveBelly** [comment]
We use operators like `concatMapEager` and `concatArrayEager` to keep the order for certain requests but we still want to parallelise as much as possible, so we can populate the list as soon as possible (in Android) without having to wait for the elements to be processed one by one in order (which is the case in Flow at the moment). Speed is paramount for us as we deal with live prices (currencies, crypto, etc)

**Comment by ExpensiveBelly** [comment]
That was quick! Many thanks. `concatMapEager` would also be really helpful.

**Comment by akarnokd** [comment]
Done via [v0.0.10](https://github.com/akarnokd/kotlin-flow-extensions/releases/tag/v0.0.10).
